"use client";

import React from "react";
import ScoreBadge from "./ScoreBadge";

interface ReportViewProps {
  report: any;
  company?: string;
}

function getRecommendationStyle(rec: string = "") {
  if (rec.includes("GOOD") || rec.includes("PROCEED")) return { bg: "rgba(76, 122, 102, 0.15)", border: "var(--color-verdigris)", color: "var(--color-verdigris)", icon: "✓" };
  if (rec.includes("CAUTION")) return { bg: "rgba(232, 163, 61, 0.15)", border: "var(--color-telemetry)", color: "var(--color-telemetry)", icon: "⚠" };
  return { bg: "rgba(178, 58, 46, 0.15)", border: "var(--color-redaction)", color: "var(--color-redaction)", icon: "✗" };
}

export default function ReportView({ report, company = "Target Company" }: ReportViewProps) {
  const recStyle = getRecommendationStyle(report?.recommendation || "");

  const copyReport = () => {
    const text = `CompanyLens Report — ${company}\n\nOverall Score: ${report?.overall_score}/10\nRecommendation: ${report?.recommendation}\n\n${report?.executive_summary}\n\nRed Flags:\n${(report?.red_flags || []).map((f: string) => `  ⚠ ${f}`).join("\n")}\n\nGreen Flags:\n${(report?.green_flags || []).map((f: string) => `  ✓ ${f}`).join("\n")}`;
    navigator.clipboard.writeText(text);
  };

  return (
    <div className="space-y-6 font-body">
      {/* Header */}
      <div className="flex justify-between items-start flex-wrap gap-4 pb-4 border-b border-[var(--color-kraft-subtle)]">
        <div>
          <h1 className="font-display text-2xl font-bold text-[var(--color-bone)]">
            DUE DILIGENCE REPORT: {company}
          </h1>
          <p className="text-xs font-mono text-[var(--color-bone-muted)] mt-1">
            Generated by CompanyLens Multi-Agent Orchestrator
          </p>
        </div>
        <button
          onClick={copyReport}
          className="px-3 py-1.5 rounded bg-[var(--color-ink)] border border-[var(--color-kraft-subtle)] text-[var(--color-telemetry)] text-xs font-mono font-semibold hover:border-[var(--color-kraft)] transition-all"
        >
          📋 COPY REPORT
        </button>
      </div>

      {/* Overall Score + Recommendation */}
      <div className="binder-card p-6 flex flex-wrap items-center gap-6 border-[var(--color-kraft-subtle)] bg-[var(--color-ink)]">
        <ScoreBadge score={report?.overall_score || 8.5} label="Overall Score" size="lg" />
        <div className="flex-1 min-w-[220px] space-y-2">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded text-xs font-mono font-bold" style={{ background: recStyle.bg, border: `1px solid ${recStyle.border}`, color: recStyle.color }}>
            <span>{recStyle.icon}</span>
            <span>{report?.recommendation || "PROCEED WITH CAUTION"}</span>
          </div>
          <p className="text-xs font-mono text-[var(--color-bone)] leading-relaxed">
            {report?.executive_summary || "Multi-agent synthesis complete. Review individual agent findings below."}
          </p>
        </div>
      </div>

      {/* 3 Score Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        {/* Legal */}
        <div className="binder-card p-4 border-[var(--color-kraft-subtle)] bg-[var(--color-ink-card)] space-y-2">
          <div className="flex items-center gap-2 text-xs font-display font-bold text-[var(--color-telemetry)] uppercase">
            <span>📋</span> Legal Scout Risk
          </div>
          <div className="text-xs font-mono text-[var(--color-bone)]">
            Risk Level: <span className="text-[var(--color-telemetry)] font-bold">{report?.legal_summary?.risk_level || "LOW"}</span>
          </div>
          {report?.legal_summary?.top_concerns && (
            <ul className="text-[11px] font-mono text-[var(--color-bone-muted)] space-y-1 pt-1">
              {report.legal_summary.top_concerns.slice(0, 3).map((c: string, idx: number) => (
                <li key={idx} className="flex gap-1">
                  <span className="text-[var(--color-telemetry)]">•</span> {c}
                </li>
              ))}
            </ul>
          )}
        </div>

        {/* Finance */}
        <div className="binder-card p-4 border-[var(--color-kraft-subtle)] bg-[var(--color-ink-card)] space-y-2">
          <div className="flex items-center gap-2 text-xs font-display font-bold text-[var(--color-kraft)] uppercase">
            <span>📊</span> Finance Analyst
          </div>
          <ScoreBadge score={report?.financial_summary?.health_score || 8.2} label="Health Score" size="sm" />
          {report?.financial_summary?.key_signals && (
            <ul className="text-[11px] font-mono text-[var(--color-bone-muted)] space-y-1 pt-1">
              {report.financial_summary.key_signals.slice(0, 3).map((s: string, idx: number) => (
                <li key={idx} className="flex gap-1">
                  <span className="text-[var(--color-kraft)]">•</span> {s}
                </li>
              ))}
            </ul>
          )}
        </div>

        {/* Dev Scout */}
        <div className="binder-card p-4 border-[var(--color-kraft-subtle)] bg-[var(--color-ink-card)] space-y-2">
          <div className="flex items-center gap-2 text-xs font-display font-bold text-[var(--color-verdigris)] uppercase">
            <span>💻</span> Dev Scout Eng Health
          </div>
          <ScoreBadge score={report?.engineering_summary?.eng_score || 9.1} label="Eng Score" size="sm" />
          {report?.engineering_summary?.highlights && (
            <ul className="text-[11px] font-mono text-[var(--color-bone-muted)] space-y-1 pt-1">
              {report.engineering_summary.highlights.slice(0, 3).map((h: string, idx: number) => (
                <li key={idx} className="flex gap-1">
                  <span className="text-[var(--color-verdigris)]">•</span> {h}
                </li>
              ))}
            </ul>
          )}
        </div>
      </div>

      {/* Red & Green Flags */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {/* Red Flags */}
        <div className="binder-card p-4 border-[var(--color-kraft-subtle)] bg-[var(--color-ink-card)]">
          <h4 className="font-display font-bold text-xs text-[var(--color-redaction)] uppercase mb-3 flex items-center gap-1.5">
            <span>⚠</span> RED FLAGS DETECTED
          </h4>
          <ul className="space-y-2 font-mono text-xs text-[var(--color-bone-muted)]">
            {(report?.red_flags || ["No major red flags detected."]).map((flag: string, idx: number) => (
              <li key={idx} className="p-2 rounded bg-[rgba(178,58,46,0.1)] border-l-2 border-[var(--color-redaction)]">
                {flag}
              </li>
            ))}
          </ul>
        </div>

        {/* Green Flags */}
        <div className="binder-card p-4 border-[var(--color-kraft-subtle)] bg-[var(--color-ink-card)]">
          <h4 className="font-display font-bold text-xs text-[var(--color-verdigris)] uppercase mb-3 flex items-center gap-1.5">
            <span>✓</span> GREEN FLAGS VERIFIED
          </h4>
          <ul className="space-y-2 font-mono text-xs text-[var(--color-bone-muted)]">
            {(report?.green_flags || ["Strong financial and engineering backing."]).map((flag: string, idx: number) => (
              <li key={idx} className="p-2 rounded bg-[rgba(76,122,102,0.1)] border-l-2 border-[var(--color-verdigris)]">
                {flag}
              </li>
            ))}
          </ul>
        </div>
      </div>
    </div>
  );
}
